/**
 * Copyright (C) 2017 Alibaba Group Holding Limited. All Rights Reserved.
 *
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __cow_codec_H
#define __cow_codec_H

#ifdef __cplusplus
extern "C" {
#endif


typedef enum {
    kCodecIDNONE,

    /* video codecs */
    kCodecIDMPEG1VIDEO,
    kCodecIDMPEG2VIDEO, ///< preferred ID for MPEG-1/2 video decoding
    kCodecIDMPEG2VIDEO_XVMC,
    kCodecIDH261,
    kCodecIDH263,
    kCodecIDRV10,
    kCodecIDRV20,
    kCodecIDMJPEG,
    kCodecIDMJPEGB,
    kCodecIDLJPEG,
    kCodecIDSP5X,
    kCodecIDJPEGLS,
    kCodecIDMPEG4,
    kCodecIDRAWVIDEO,
    kCodecIDMSMPEG4V1,
    kCodecIDMSMPEG4V2,
    kCodecIDMSMPEG4V3,
    kCodecIDWMV1,
    kCodecIDWMV2,
    kCodecIDH263P,
    kCodecIDH263I,
    kCodecIDFLV1,
    kCodecIDSVQ1,
    kCodecIDSVQ3,
    kCodecIDDVVIDEO,
    kCodecIDHUFFYUV,
    kCodecIDCYUV,
    kCodecIDH264,
    kCodecIDINDEO3,
    kCodecIDVP3,
    kCodecIDTHEORA,
    kCodecIDASV1,
    kCodecIDASV2,
    kCodecIDFFV1,
    kCodecID4XM,
    kCodecIDVCR1,
    kCodecIDCLJR,
    kCodecIDMDEC,
    kCodecIDROQ,
    kCodecIDINTERPLAY_VIDEO,
    kCodecIDXAN_WC3,
    kCodecIDXAN_WC4,
    kCodecIDRPZA,
    kCodecIDCINEPAK,
    kCodecIDWS_VQA,
    kCodecIDMSRLE,
    kCodecIDMSVIDEO1,
    kCodecIDIDCIN,
    kCodecID8BPS,
    kCodecIDSMC,
    kCodecIDFLIC,
    kCodecIDTRUEMOTION1,
    kCodecIDVMDVIDEO,
    kCodecIDMSZH,
    kCodecIDZLIB,
    kCodecIDQTRLE,
    kCodecIDTSCC,
    kCodecIDULTI,
    kCodecIDQDRAW,
    kCodecIDVIXL,
    kCodecIDQPEG,
    kCodecIDPNG,
    kCodecIDPPM,
    kCodecIDPBM,
    kCodecIDPGM,
    kCodecIDPGMYUV,
    kCodecIDPAM,
    kCodecIDFFVHUFF,
    kCodecIDRV30,
    kCodecIDRV40,
    kCodecIDVC1,
    kCodecIDWMV3,
    kCodecIDLOCO,
    kCodecIDWNV1,
    kCodecIDAASC,
    kCodecIDINDEO2,
    kCodecIDFRAPS,
    kCodecIDTRUEMOTION2,
    kCodecIDBMP,
    kCodecIDCSCD,
    kCodecIDMMVIDEO,
    kCodecIDZMBV,
    kCodecIDAVS,
    kCodecIDSMACKVIDEO,
    kCodecIDNUV,
    kCodecIDKMVC,
    kCodecIDFLASHSV,
    kCodecIDCAVS,
    kCodecIDJPEG2000,
    kCodecIDVMNC,
    kCodecIDVP5,
    kCodecIDVP6,
    kCodecIDVP6F,
    kCodecIDTARGA,
    kCodecIDDSICINVIDEO,
    kCodecIDTIERTEXSEQVIDEO,
    kCodecIDTIFF,
    kCodecIDGIF,
    kCodecIDDXA,
    kCodecIDDNXHD,
    kCodecIDTHP,
    kCodecIDSGI,
    kCodecIDC93,
    kCodecIDBETHSOFTVID,
    kCodecIDPTX,
    kCodecIDTXD,
    kCodecIDVP6A,
    kCodecIDAMV,
    kCodecIDVB,
    kCodecIDPCX,
    kCodecIDSUNRAST,
    kCodecIDINDEO4,
    kCodecIDINDEO5,
    kCodecIDMIMIC,
    kCodecIDRL2,
    kCodecIDESCAPE124,
    kCodecIDDIRAC,
    kCodecIDBFI,
    kCodecIDCMV,
    kCodecIDMOTIONPIXELS,
    kCodecIDTGV,
    kCodecIDTGQ,
    kCodecIDTQI,
    kCodecIDAURA,
    kCodecIDAURA2,
    kCodecIDV210X,
    kCodecIDTMV,
    kCodecIDV210,
    kCodecIDDPX,
    kCodecIDMAD,
    kCodecIDFRWU,
    kCodecIDFLASHSV2,
    kCodecIDCDGRAPHICS,
    kCodecIDR210,
    kCodecIDANM,
    kCodecIDBINKVIDEO,
    kCodecIDIFF_ILBM,
    kCodecIDKGV1,
    kCodecIDYOP,
    kCodecIDVP8,
    kCodecIDPICTOR,
    kCodecIDANSI,
    kCodecIDA64_MULTI,
    kCodecIDA64_MULTI5,
    kCodecIDR10K,
    kCodecIDMXPEG,
    kCodecIDLAGARITH,
    kCodecIDPRORES,
    kCodecIDJV,
    kCodecIDDFA,
    kCodecIDWMV3IMAGE,
    kCodecIDVC1IMAGE,
    kCodecIDUTVIDEO,
    kCodecIDBMV_VIDEO,
    kCodecIDVBLE,
    kCodecIDDXTORY,
    kCodecIDV410,
    kCodecIDXWD,
    kCodecIDCDXL,
    kCodecIDXBM,
    kCodecIDZEROCODEC,
    kCodecIDMSS1,
    kCodecIDMSA1,
    kCodecIDTSCC2,
    kCodecIDMTS2,
    kCodecIDCLLC,
    kCodecIDMSS2,
    kCodecIDVP9,
    kCodecIDAIC,
    kCodecIDESCAPE130,
    kCodecIDG2M,
    kCodecIDWEBP,
    kCodecIDHNM4_VIDEO,
    kCodecIDHEVC,
    kCodecIDFIC,
    kCodecIDALIAS_PIX,
    kCodecIDBRENDER_PIX,
    kCodecIDPAF_VIDEO,
    kCodecIDEXR,
    kCodecIDVP7,
    kCodecIDSANM,
    kCodecIDSGIRLE,
    kCodecIDMVC1,
    kCodecIDMVC2,
    kCodecIDHQX,
    kCodecIDTDSC,
    kCodecIDHQ_HQA,
    kCodecIDHAP,
    kCodecIDDDS,
    kCodecIDDXV,
    kCodecIDSCREENPRESSO,
    kCodecIDRSCC,

    kCodecIDY41P = 0x8000,
    kCodecIDAVRP,
    kCodecID012V,
    kCodecIDAVUI,
    kCodecIDAYUV,
    kCodecIDTARGA_Y216,
    kCodecIDV308,
    kCodecIDV408,
    kCodecIDYUV4,
    kCodecIDAVRN,
    kCodecIDCPIA,
    kCodecIDXFACE,
    kCodecIDSNOW,
    kCodecIDSMVJPEG,
    kCodecIDAPNG,
    kCodecIDDAALA,
    kCodecIDCFHD,
    kCodecIDTRUEMOTION2RT,
    kCodecIDM101,
    kCodecIDMAGICYUV,
    kCodecIDSHEERVIDEO,
    kCodecIDYLC,

    /* various PCM "codecs" */
    kCodecIDFIRST_AUDIO = 0x10000,     ///< A dummy id pointing at the start of audio codecs
    kCodecIDPCM_S16LE = 0x10000,
    kCodecIDPCM_S16BE,
    kCodecIDPCM_U16LE,
    kCodecIDPCM_U16BE,
    kCodecIDPCM_S8,
    kCodecIDPCM_U8,
    kCodecIDPCM_MULAW,
    kCodecIDPCM_ALAW,
    kCodecIDPCM_S32LE,
    kCodecIDPCM_S32BE,
    kCodecIDPCM_U32LE,
    kCodecIDPCM_U32BE,
    kCodecIDPCM_S24LE,
    kCodecIDPCM_S24BE,
    kCodecIDPCM_U24LE,
    kCodecIDPCM_U24BE,
    kCodecIDPCM_S24DAUD,
    kCodecIDPCM_ZORK,
    kCodecIDPCM_S16LE_PLANAR,
    kCodecIDPCM_DVD,
    kCodecIDPCM_F32BE,
    kCodecIDPCM_F32LE,
    kCodecIDPCM_F64BE,
    kCodecIDPCM_F64LE,
    kCodecIDPCM_BLURAY,
    kCodecIDPCM_LXF,
    kCodecIDS302M,
    kCodecIDPCM_S8_PLANAR,
    kCodecIDPCM_S24LE_PLANAR,
    kCodecIDPCM_S32LE_PLANAR,
    kCodecIDPCM_S16BE_PLANAR,

    kCodecIDPCM_S64LE = 0x10800,
    kCodecIDPCM_S64BE,

    /* various ADPCM codecs */
    kCodecIDADPCM_IMA_QT = 0x11000,
    kCodecIDADPCM_IMA_WAV,
    kCodecIDADPCM_IMA_DK3,
    kCodecIDADPCM_IMA_DK4,
    kCodecIDADPCM_IMA_WS,
    kCodecIDADPCM_IMA_SMJPEG,
    kCodecIDADPCM_MS,
    kCodecIDADPCM_4XM,
    kCodecIDADPCM_XA,
    kCodecIDADPCM_ADX,
    kCodecIDADPCM_EA,
    kCodecIDADPCM_G726,
    kCodecIDADPCM_CT,
    kCodecIDADPCM_SWF,
    kCodecIDADPCM_YAMAHA,
    kCodecIDADPCM_SBPRO_4,
    kCodecIDADPCM_SBPRO_3,
    kCodecIDADPCM_SBPRO_2,
    kCodecIDADPCM_THP,
    kCodecIDADPCM_IMA_AMV,
    kCodecIDADPCM_EA_R1,
    kCodecIDADPCM_EA_R3,
    kCodecIDADPCM_EA_R2,
    kCodecIDADPCM_IMA_EA_SEAD,
    kCodecIDADPCM_IMA_EA_EACS,
    kCodecIDADPCM_EA_XAS,
    kCodecIDADPCM_EA_MAXIS_XA,
    kCodecIDADPCM_IMA_ISS,
    kCodecIDADPCM_G722,
    kCodecIDADPCM_IMA_APC,
    kCodecIDADPCM_VIMA,

    kCodecIDADPCM_AFC = 0x11800,
    kCodecIDADPCM_IMA_OKI,
    kCodecIDADPCM_DTK,
    kCodecIDADPCM_IMA_RAD,
    kCodecIDADPCM_G726LE,
    kCodecIDADPCM_THP_LE,
    kCodecIDADPCM_PSX,
    kCodecIDADPCM_AICA,
    kCodecIDADPCM_IMA_DAT4,
    kCodecIDADPCM_MTAF,

    /* AMR */
    kCodecIDAMR_NB = 0x12000,
    kCodecIDAMR_WB,

    /* RealAudio codecs*/
    kCodecIDRA_144 = 0x13000,
    kCodecIDRA_288,

    /* various DPCM codecs */
    kCodecIDROQ_DPCM = 0x14000,
    kCodecIDINTERPLAY_DPCM,
    kCodecIDXAN_DPCM,
    kCodecIDSOL_DPCM,

    kCodecIDSDX2_DPCM = 0x14800,

    /* audio codecs */
    kCodecIDMP2 = 0x15000,
    kCodecIDMP3, ///< preferred ID for decoding MPEG audio layer 1, 2 or 3
    kCodecIDAAC,
    kCodecIDAC3,
    kCodecIDDTS,
    kCodecIDVORBIS,
    kCodecIDDVAUDIO,
    kCodecIDWMAV1,
    kCodecIDWMAV2,
    kCodecIDMACE3,
    kCodecIDMACE6,
    kCodecIDVMDAUDIO,
    kCodecIDFLAC,
    kCodecIDMP3ADU,
    kCodecIDMP3ON4,
    kCodecIDSHORTEN,
    kCodecIDALAC,
    kCodecIDWESTWOOD_SND1,
    kCodecIDGSM, ///< as in Berlin toast format
    kCodecIDQDM2,
    kCodecIDCOOK,
    kCodecIDTRUESPEECH,
    kCodecIDTTA,
    kCodecIDSMACKAUDIO,
    kCodecIDQCELP,
    kCodecIDWAVPACK,
    kCodecIDDSICINAUDIO,
    kCodecIDIMC,
    kCodecIDMUSEPACK7,
    kCodecIDMLP,
    kCodecIDGSM_MS, /* as found in WAV */
    kCodecIDATRAC3,
    kCodecIDVOXWARE,
    kCodecIDAPE,
    kCodecIDNELLYMOSER,
    kCodecIDMUSEPACK8,
    kCodecIDSPEEX,
    kCodecIDWMAVOICE,
    kCodecIDWMAPRO,
    kCodecIDWMALOSSLESS,
    kCodecIDATRAC3P,
    kCodecIDEAC3,
    kCodecIDSIPR,
    kCodecIDMP1,
    kCodecIDTWINVQ,
    kCodecIDTRUEHD,
    kCodecIDMP4ALS,
    kCodecIDATRAC1,
    kCodecIDBINKAUDIO_RDFT,
    kCodecIDBINKAUDIO_DCT,
    kCodecIDAAC_LATM,
    kCodecIDQDMC,
    kCodecIDCELT,
    kCodecIDG723_1,
    kCodecIDG729,
    kCodecID8SVX_EXP,
    kCodecID8SVX_FIB,
    kCodecIDBMV_AUDIO,
    kCodecIDRALF,
    kCodecIDIAC,
    kCodecIDILBC,
    kCodecIDOPUS,
    kCodecIDCOMFORT_NOISE,
    kCodecIDTAK,
    kCodecIDMETASOUND,
    kCodecIDPAF_AUDIO,
    kCodecIDON2AVC,
    kCodecIDDSS_SP,

    kCodecIDFFWAVESYNTH = 0x15800,
    kCodecIDSONIC,
    kCodecIDSONIC_LS,
    kCodecIDEVRC,
    kCodecIDSMV,
    kCodecIDDSD_LSBF,
    kCodecIDDSD_MSBF,
    kCodecIDDSD_LSBF_PLANAR,
    kCodecIDDSD_MSBF_PLANAR,
    kCodecID4GV,
    kCodecIDINTERPLAY_ACM,
    kCodecIDXMA1,
    kCodecIDXMA2,
    kCodecIDDST,

    /* subtitle codecs */
    kCodecIDFIRST_SUBTITLE = 0x17000,          ///< A dummy ID pointing at the start of subtitle codecs.
    kCodecIDDVD_SUBTITLE = 0x17000,
    kCodecIDDVB_SUBTITLE,
    kCodecIDTEXT,  ///< raw UTF-8 text
    kCodecIDXSUB,
    kCodecIDSSA,
    kCodecIDMOV_TEXT,
    kCodecIDHDMV_PGS_SUBTITLE,
    kCodecIDDVB_TELETEXT,
    kCodecIDSRT,

    kCodecIDMICRODVD   = 0x17800,
    kCodecIDEIA_608,
    kCodecIDJACOSUB,
    kCodecIDSAMI,
    kCodecIDREALTEXT,
    kCodecIDSTL,
    kCodecIDSUBVIEWER1,
    kCodecIDSUBVIEWER,
    kCodecIDSUBRIP,
    kCodecIDWEBVTT,
    kCodecIDMPL2,
    kCodecIDVPLAYER,
    kCodecIDPJS,
    kCodecIDASS,
    kCodecIDHDMV_TEXT_SUBTITLE,

    /* other specific kind of codecs (generally used for attachments) */
    kCodecIDFIRST_UNKNOWN = 0x18000,           ///< A dummy ID pointing at the start of various fake codecs.
    kCodecIDTTF = 0x18000,

    kCodecIDBINTEXT    = 0x18800,
    kCodecIDXBIN,
    kCodecIDIDF,
    kCodecIDOTF,
    kCodecIDSMPTE_KLV,
    kCodecIDDVD_NAV,
    kCodecIDTIMED_ID3,
    kCodecIDBIN_DATA,

    kCodecIDPROBE = 0x19000, ///< codec_id is not known (like kCodecIDNONE) but lavf should attempt to identify it

    kCodecIDMPEG2TS = 0x20000, /**< _FAKE_ codec to indicate a raw MPEG-2 TS
                                * stream (only used by libavformat) */
    kCodecIDMPEG4SYSTEMS = 0x20001, /**< _FAKE_ codec to indicate a MPEG-4 Systems
                                * stream (only used by libavformat) */
    kCodecIDFFMETADATA = 0x21000,   ///< Dummy codec for streams containing only metadata information.
    kCodecIDWRAPPED_AVFRAME = 0x21001, ///< Passthrough codec, AVFrames wrapped in AVPacket
} CowCodecID;
#ifdef __cplusplus
}
#endif

#endif // __cow_codec_H
